name: Rails CI

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: [ '2.6', '2.7' ]

    steps:
      - run: sudo apt update -y; sudo apt install -y libsqlite3-dev
      - uses: actions/checkout@v2
      - name: Use Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: bundle install and tests
        run: |
          gem install bundler
          bundle install
          bundle exec rspec
        env:
          RAILS_ENV: test

  # build-windows:
  #   runs-on: windows-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Ruby ${{ matrix.ruby }}
  #       uses: actions/setup-ruby@v1
  #       with:
  #         ruby-version: 2.6
  #     - name: bundle install and tests
  #       run: |
  #         gem install bundler
  #         bundle install
  #         bundle exec rspec
  #       env:
  #         RAILS_ENV: test
